version: '2.1'
services:
  moodle:
    image: git.lambdasolutions.net:5555/composer-profiles/sandbox-profile
    links:
      - moodle_db
    ports:
      - "8080:8080"
    volumes:
       - ./moodledata:/var/www/data/default/moodledata
    restart: always
 
  moodle_db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always
